# Generated by Django 5.1.4 on 2024-12-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('utype', models.CharField(max_length=50)),
                ('uid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('ugender', models.CharField(max_length=10)),
                ('uphone', models.CharField(max_length=20, unique=True)),
                ('upassword', models.CharField(max_length=100)),
            ],
        ),
    ]
