# Generated by Django 5.1.4 on 2024-12-18 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('cid', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='电影院编号')),
                ('cname', models.CharField(max_length=255, verbose_name='电影院名称')),
            ],
            options={
                'db_table': 'cinema',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('mid', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='电影编号')),
                ('mtime', models.BigIntegerField(verbose_name='影片时长(分钟)')),
                ('mname', models.CharField(max_length=255, verbose_name='电影名称')),
                ('mhot', models.CharField(max_length=255, verbose_name='影片热度')),
                ('mscore', models.FloatField(verbose_name='影片评分')),
                ('myear', models.DateField(verbose_name='上线时间')),
                ('mtext', models.CharField(max_length=255, verbose_name='简介')),
                ('mcommit', models.CharField(max_length=255, verbose_name='评论')),
                ('mpicture', models.CharField(max_length=255, verbose_name='封面名称')),
                ('mpost', models.CharField(max_length=255, verbose_name='海报名称')),
                ('mintro', models.CharField(max_length=255, verbose_name='电影简介')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('pid', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='来源地编号')),
                ('pname', models.CharField(max_length=255, verbose_name='来源地')),
            ],
            options={
                'db_table': 'place',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seatid', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='布局编号')),
                ('seats', models.CharField(max_length=255, verbose_name='座位情况')),
            ],
            options={
                'db_table': 'seat',
            },
        ),
        migrations.CreateModel(
            name='SeatModel',
            fields=[
                ('sid', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='布局模板编号')),
                ('smodel', models.CharField(max_length=255, verbose_name='座位布局')),
            ],
            options={
                'db_table': 'seat_model',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('tid', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='类型编号')),
                ('tname', models.CharField(max_length=255, verbose_name='类型名称')),
            ],
            options={
                'db_table': 'type',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='ugender',
            field=models.CharField(max_length=255, verbose_name='用户性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='用户编号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='upassword',
            field=models.CharField(max_length=255, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uphone',
            field=models.CharField(max_length=255, verbose_name='用户手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='utype',
            field=models.CharField(max_length=255, verbose_name='用户等级'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('hid', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='影厅编号')),
                ('hname', models.CharField(max_length=255, verbose_name='影厅名称')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cinema', verbose_name='所属影院编号')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.seatmodel', verbose_name='座位布局编号')),
            ],
            options={
                'db_table': 'hall',
            },
        ),
        migrations.CreateModel(
            name='FilmArrangement',
            fields=[
                ('fid', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='排片编号')),
                ('fstarttime', models.DateTimeField(verbose_name='开播时间')),
                ('fendtime', models.DateTimeField(verbose_name='结束时间')),
                ('fcost', models.BigIntegerField(verbose_name='定价')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cinema', verbose_name='所在影院')),
                ('hid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hall', verbose_name='所在影厅')),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.movie', verbose_name='所播电影')),
                ('seatid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.seat', verbose_name='布局编号')),
            ],
            options={
                'db_table': 'film_arrangement',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('oid', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='订单编号')),
                ('otime', models.DateTimeField(verbose_name='下单时间')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.filmarrangement', verbose_name='下单排片编号')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='下单用户编号')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.place', verbose_name='来源地编号'),
        ),
        migrations.AddField(
            model_name='seat',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.seatmodel', verbose_name='布局模板编号'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.type', verbose_name='类型编号'),
        ),
    ]
