# Generated by Django 5.1.4 on 2024-12-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cinema_movie_place_seat_seatmodel_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='mcommit',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='mintro',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='mpicture',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='mpost',
        ),
        migrations.AlterField(
            model_name='movie',
            name='mhot',
            field=models.BigIntegerField(verbose_name='影片热度'),
        ),
    ]
