# Generated by Django 5.1.4 on 2024-12-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_movie_mcommit_remove_movie_mintro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seats',
            field=models.TextField(verbose_name='座位情况'),
        ),
        migrations.AlterField(
            model_name='seatmodel',
            name='smodel',
            field=models.TextField(verbose_name='座位布局'),
        ),
    ]
