# Generated by Django 5.1.4 on 2024-12-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_seat_seats_alter_seatmodel_smodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmarrangement',
            name='fid',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='排片编号'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='oid',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seatid',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='布局编号'),
        ),
    ]
