# Generated by Django 5.1.4 on 2024-12-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_filmarrangement_fid_alter_orders_oid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='pid',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='来源地编号'),
        ),
        migrations.AlterField(
            model_name='type',
            name='tid',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='类型编号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='用户编号'),
        ),
    ]
