# Generated by Django 5.1.4 on 2024-12-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_cinema_cid_alter_hall_hid_alter_movie_mid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='oprice',
            field=models.BigIntegerField(default=0, verbose_name='花费金额'),
        ),
        migrations.AddField(
            model_name='orders',
            name='oseats',
            field=models.TextField(default='0', verbose_name='所定座位'),
        ),
    ]
