# Generated by Django 5.1.4 on 2024-12-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_orders_oprice_orders_oseats'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmarrangement',
            name='f_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='h_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='m_active',
            field=models.BooleanField(default=True),
        ),
    ]
