# Generated by Django 5.1.4 on 2024-12-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_filmarrangement_f_active_hall_h_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='oid',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='订单编号'),
        ),
    ]
