# Generated by Django 5.1.4 on 2024-12-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_orders_oid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmarrangement',
            name='fid',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='排片编号'),
        ),
    ]
